# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 16:58
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161214_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=accounts.models.PhoneNumberField(blank=True, help_text="'-' 없이 번호를 입력해주세요.", max_length=12, validators=[accounts.models.phonenumber_validator, accounts.models.phonenumber_validator, accounts.models.phonenumber_validator]),
        ),
    ]
