# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='attend_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='penalty_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
