# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20160530_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attend_count',
            field=models.IntegerField(default=0),
        ),
    ]
