# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20160628_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gps_x',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gps_y',
        ),
        migrations.AddField(
            model_name='post',
            name='meeting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='recruit_status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
