# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attend_count',
            field=models.IntegerField(default=1),
        ),
    ]
