# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recruit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('registered_date', models.DateTimeField(default=recruit.models.change_timezone)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('registered_date', models.DateTimeField(default=recruit.models.change_timezone)),
                ('recruit_count', models.IntegerField()),
                ('attend_count', models.IntegerField(default=0)),
                ('recruit_status', models.IntegerField(choices=[(0, '모집중'), (1, '모집완료')], default=0)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('comment_count', models.IntegerField(default=0)),
                ('latlng', models.CharField(blank=True, default='37.497921,127.027636', max_length=50)),
                ('meeting_date', models.DateTimeField(default=recruit.models.change_timezone)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registered_date',),
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='recruit.Post'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recruit.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('post', 'user')]),
        ),
    ]
