# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20160530_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recruit',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
