# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20160530_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latlng',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
