# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_post_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recruit_status',
            field=models.CharField(default='ing', max_length=20),
        ),
    ]
